include the Tcl/Tk dependencies that are needed for script GUIs
To prevent 

```Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "././/share/scribus/scripts/FontSample.py", line 1577, in <module>
    main_wrapper(sys.argv)
  File "././/share/scribus/scripts/FontSample.py", line 1562, in main_wrapper
    main(argv)
  File "././/share/scribus/scripts/FontSample.py", line 1551, in main
    initialisation()
  File "././/share/scribus/scripts/FontSample.py", line 1544, in initialisation
    app = setup_tk()
  File "././/share/scribus/scripts/FontSample.py", line 1512, in setup_tk
    root = Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: Can't find a usable init.tcl in the following directories: 
    /usr/share/tcltk/tcl8.6 /usr/lib/tcl8.6 /lib/tcl8.6 /usr/library /library /tcl8.6.1/library /tcl8.6.1/library

/usr/share/tcltk/tcl8.6/init.tcl: version conflict for package "Tcl": have 8.6.1, need exactly 8.6.5
version conflict for package "Tcl": have 8.6.1, need exactly 8.6.5
    while executing
"package require -exact Tcl 8.6.5"
    (file "/usr/share/tcltk/tcl8.6/init.tcl" line 19)
    invoked from within
"source /usr/share/tcltk/tcl8.6/init.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $tclfile]"
```